<?php
echo "<b>Registrier Test 1</b><br>";
echo "E-Mail: <br>";
echo "Benutzername: <br>";
echo "Passwort: <br>";
echo "Passwort WD: <br>";
$test = array();
$test["EMAIL"] = "";
$test["USERNAME"] = "";
$test["PASSWORD"] = "";
$test["PASSWORD_WD"] = "";
$_POST["DATA"] = JSON_ENCODE($test);
include("../register.php");
echo "<br><br>";

echo "<b>Registrier Test 2</b><br>";
echo "E-Mail: Test@Test.de<br>";
echo "Benutzername: <br>";
echo "Passwort: <br>";
echo "Passwort WD: <br>";
$test = array();
$test["EMAIL"] = "Test@Test.de";
$test["USERNAME"] = "";
$test["PASSWORD"] = "";
$test["PASSWORD_WD"] = "";
$_POST["DATA"] = JSON_ENCODE($test);
include("../register.php");
echo "<br><br>";

echo "<b>Registrier Test 3</b><br>";
echo "E-Mail: Test@Test.de<br>";
echo "Benutzername: Test<br>";
echo "Passwort: <br>";
echo "Passwort WD: <br>";
$test = array();
$test["EMAIL"] = "Test@Test.de";
$test["USERNAME"] = "Test";
$test["PASSWORD"] = "";
$test["PASSWORD_WD"] = "";
$_POST["DATA"] = JSON_ENCODE($test);
include("../register.php");
echo "<br><br>";

echo "<b>Registrier Test 4</b><br>";
echo "E-Mail: Test@Test.de<br>";
echo "Benutzername: Test<br>";
echo "Passwort: P@ssw0rd<br>";
echo "Passwort WD: <br>";
$test = array();
$test["EMAIL"] = "Test@Test.de";
$test["USERNAME"] = "Test";
$test["PASSWORD"] = "P@ssw0rd";
$test["PASSWORD_WD"] = "";
$_POST["DATA"] = JSON_ENCODE($test);
include("../register.php");
echo "<br><br>";

echo "<b>Registrier Test 5</b><br>";
echo "E-Mail: Test@Test.de<br>";
echo "Benutzername: Test<br>";
echo "Passwort: <br>";
echo "Passwort WD: P@ssw0rd<br>";
$test = array();
$test["EMAIL"] = "Test@Test.de";
$test["USERNAME"] = "Test";
$test["PASSWORD"] = "";
$test["PASSWORD_WD"] = "P@ssw0rd";
$_POST["DATA"] = JSON_ENCODE($test);
include("../register.php");
echo "<br><br>";

echo "<b>Registrier Test 6</b><br>";
echo "E-Mail: Test@Test.de<br>";
echo "Benutzername: Test<br>";
echo "Passwort: P@ssw0rd<br>";
echo "Passwort WD: P@sswort<br>";
$test = array();
$test["EMAIL"] = "Test@Test.de";
$test["USERNAME"] = "Test";
$test["PASSWORD"] = "P@ssw0rd";
$test["PASSWORD_WD"] = "P@ssw0rt";
$_POST["DATA"] = JSON_ENCODE($test);
include("../register.php");
echo "<br><br>";

echo "<b>Registrier Test 7</b><br>";
echo "E-Mail: Test@Test.de<br>";
echo "Benutzername: Test<br>";
echo "Passwort: P@ssw0rd<br>";
echo "Passwort WD: P@ssw0rd<br>";
$test = array();
$test["EMAIL"] = "Test@Test.de";
$test["USERNAME"] = "Test";
$test["PASSWORD"] = "P@ssw0rd";
$test["PASSWORD_WD"] = "P@ssw0rd";
$_POST["DATA"] = JSON_ENCODE($test);
include("../register.php");
echo "<br><br>";

echo "<b>Registrier Test 8</b><br>";
echo "E-Mail: Test@Test.de<br>";
echo "Benutzername: Test<br>";
echo "Passwort: P@ssw0rd<br>";
echo "Passwort WD: P@ssw0rd<br>";
$test = array();
$test["EMAIL"] = "Test@Test.de";
$test["USERNAME"] = "Test";
$test["PASSWORD"] = "P@ssw0rd";
$test["PASSWORD_WD"] = "P@ssw0rd";
$_POST["DATA"] = JSON_ENCODE($test);
include("../register.php");
echo "<br><br>"; ?>